apiVersion: v1
kind: Pod
metadata:
  name: anchors
  labels:
    app: anchors
spec:
  containers:
  - name: main-container
    image: nginx
    resources: &resources  #define an anchor for resources limit
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  - name: sidecar-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources: *resources  #use the anchor for resources limit