apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
  labels:
    app: multicontainer
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumes:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]
      volumeMounts:
        - name: shared-volume
          mountPath: /var/temp # This is where the busybox container will write data
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
  volumes:
    - name: shared-volume
      emptyDir: 
        medium: Memory # This volume will be shared between the containers
        

  restartPolicy: Always