apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    env: prod
spec:
  containers:
    - name: nginx
      image: nginx:1.22
      ports:
        - containerPort: 80
      volumeMounts:   # This is where the volume will be mounted in the container.
        - name: nginx-volume
          mountPath: /usr/share/nginx/html # This data will be stored in the nginx-volume volume.

  volumes:
    - name: nginx-volume
      emptyDir: {}   # This volume is created when the Pod is assigned to a Node and exists as long as that Pod is running on that Node.


