apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
    env: dev

spec:
  containers:
    - name: nginx-app
      image: nginx:1.22.0
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD 
          value: "password"
      resources:
        requests:
          memory: "64Mi" # Mi = Mebibyte = 1024 * 1024 bytes 1Gi = 1024 * 1024 * 1024 bytes means 1Gi = 1024Mi
          cpu: "250m"    # 1 core cpu = 1000m
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config